---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.4.4
  use_vagrant_berkshelf_plugin: true
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  customize:
    memory: 1024
    cpus: 2

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
  run_list: ["recipe[apt]"]

suites:
- name: default
  run_list:
  - recipe[martinisoft-postgresql::default]
  - recipe[postgresql::server]
  - recipe[postgresql::contrib]
  - recipe[martinisoft-nginx::default]
  - recipe[funnies::default]
  encrypted_data_bag_secret_key_path: test/integration/default/data_bags/encrypted_data_bag_secret
  attributes: {}
